### ISSUE TITLE
Automatisierter Stundenplan

### ISSUE THREAD

**Issue by jan2210** [TotallyInformatik/annette_app_3.0#4]
Bei automatisiertem Stundenplan-Upload relevant:

Verwendungen der stundenplan.txt Datei:
- onlineFiles.dart
- update.dart

**Comment by 123654-dev** [comment]
Der Stundenplan wird nun automatisch und zuverlässig für den aktuellen Tag aktualisiert (in der API ist aktuell zu Testzwecken der 13. Juni 2022 festgelegt). Als nächstes könnten eventuell Optionen für andere Daten als den aktuellen Tag oder ein Feature, durch das der Stundenplan nur aktualisiert wird, wenn die lokale Version veraltet ist, in API und App implementiert werden.

**Comment by TotallyInformatik** [comment]
Den Code habe ich eben getestet. 

Das meiste scheint zu klappen jedoch gibt es zwei Probleme:
1. Manchmal funktionieren einige Api-Endpoints zwischenzeitlich nicht (bei 5e ist zunächst ein statuscode von 500 aufgetaucht, wenn man die Seite refreshed hat, hat der Endpoint wieder funktioniert)
2. Api-Endpoint q1 funktioniert nicht

**Comment by 123654-dev** [comment]
> 3. Auf dem neusten production deployment von der webuntis-api (https://annette-entwickelt-software-p82z6c98o-totallyinformatik.vercel.app), funktioniert scheinbar keine Klasse.

Ja, auf dem Production Deployment ist momentan noch das aktuelle Datum eingestellt, und da Ferien sind, findet keine Schule statt.

> Liegt es an dem Datum? Ist es möglich, fürs erste den letzten Schultag vom letzten Schuljahr als Datum für Testzwecken festzulegen?

Dieses Datum ist auf dem Test-Deployment auf den 13. 06. hardgecoded, da aktuell ein Wochenende ist, die App daher also den Stundenplan für einen Montag anzeigen würde und dieses Datum ebenfalls ein Montag ist. Es kann in der API auf einen beliebigen anderen Wochentag festgelegt werden, mit einer Möglichkeit, das Datum evtl. in der URL festlegen zu können, habe ich ein wenig experimentiert, das funktioniert aber noch nicht.

Der Status-500-Fehler ist sehr merkwürdig, ich gucke mir das Problem noch mal an.
